"""Copy the runtime art into the game and write the GDScript lookup tables.

    python3 art/tools/export_game.py      (after texgen.py, build_atlas.py, icongen.py)

Writes:
  assets/textures/block_textures.png    (= art/textures/atlas_array.png, 16 x 16*N strip)
  assets/icons/item_icons.png           (= art/icons/icon_atlas.png)
  src/core/block_textures.gd            (GENERATED: layer numbers, biome surfaces)
  src/ui/item_icon_atlas.gd             (GENERATED: item id -> icon cell)
  *.png.import files (lossless, no mipmaps: the game builds mipmaps itself)

The whole art/ folder is hidden from Godot (art/.gdignore): it is source art.
"""
import hashlib
import json
import os
import shutil

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
ATLAS = json.load(open(os.path.join(ROOT, "art", "textures", "atlas.json")))
ICONS = json.load(open(os.path.join(ROOT, "art", "icons", "icon_atlas.json")))

IMPORT = """[remap]

importer="texture"
type="CompressedTexture2D"
path="res://.godot/imported/{name}-{md5}.ctex"
metadata={{
"vram_texture": false
}}

[deps]

source_file="{res}"
dest_files=["res://.godot/imported/{name}-{md5}.ctex"]

[params]

compress/mode=0
compress/high_quality=false
compress/lossy_quality=0.7
compress/hdr_compression=1
compress/normal_map=0
compress/channel_pack=0
mipmaps/generate=false
mipmaps/limit=-1
roughness/mode=0
roughness/src_normal=""
process/fix_alpha_border=false
process/premult_alpha=false
process/normal_map_invert_y=false
process/hdr_as_srgb=false
process/hdr_clamp_exposure=false
process/size_limit=0
detect_3d/compress_to=0
"""


def copy_with_import(src, rel):
    dst = os.path.join(ROOT, rel)
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    shutil.copyfile(src, dst)
    res = "res://" + rel.replace(os.sep, "/")
    name = os.path.basename(rel)
    imp = dst + ".import"
    text = IMPORT.format(name=name, md5=hashlib.md5(res.encode()).hexdigest(), res=res)
    # keep an existing uid line if the editor already added one
    if os.path.exists(imp):
        for line in open(imp):
            if line.startswith("uid="):
                text = text.replace('type="CompressedTexture2D"\n', 'type="CompressedTexture2D"\n' + line)
    open(imp, "w").write(text)


def gd_list(v):
    return "[" + ", ".join(str(x) for x in v) + "]"


def block_textures_gd():
    tex = ATLAS["textures"]
    layer = {n: t["layer"] for n, t in tex.items()}
    L = lambda n: layer[n]
    out = [
        "class_name BlockTextures",
        "## GENERATED by art/tools/export_game.py from art/textures/atlas.json - do not edit by hand.",
        "## Layer numbers of the block texture array (assets/textures/block_textures.png, one",
        "## 16 x 16 texture per layer) and which layers each biome surface uses. See docs/ART_BIBLE.md.",
        "",
        'const ARRAY_PATH := "res://assets/textures/block_textures.png"',
        "const SIZE := 16",
        f"const COUNT := {len(tex)}",
        "## Tinted textures are multiplied by this (a stored 0.8 = no change).",
        f"const GAIN := {ATLAS['tex_gain']}",
        "",
        "const LAYER := {",
    ]
    out += [f'\t&"{n}": {i},' for n, i in layer.items()]
    out += ["}", "", "## Layers stored in real colours (multiply a white vertex colour).", "const FULL := {"]
    out += [f'\t&"{n}": true,' for n, t in tex.items() if t["tint"] == "full"]
    out += ["}", "", "## Layers drawn as crossed cut-out cards (plants).", "const SPRITE := {"]
    out += [f'\t&"{n}": true,' for n, t in tex.items() if t["face"] == "sprite"]
    out += ["}", "",
            "## Biome id -> surface layers. \"top\" lists are variants (pick one per block by hash);",
            "## \"edge\" is the grass-edge band (alpha mask), \"side\" the wall below it.",
            "const BIOMES := {"]
    for b, d in ATLAS["biomes"].items():
        s = d["surfaces"]
        e = {
            "top": gd_list([L(n) for n in s["top"]["top"]]), "edge": L(s["top"]["edge"]), "side": L(s["top"]["side"]),
            "shore": gd_list([L(n) for n in s["shore"]["top"]]), "shore_edge": L(s["shore"]["edge"]), "shore_side": L(s["shore"]["side"]),
            "underwater": gd_list([L(n) for n in s["underwater"]["top"]]), "underwater_side": L(s["underwater"]["side"]),
            "rock": gd_list([L(n) for n in s["rock"]["top"]]), "rock_edge": L(s["rock"]["edge"]), "rock_side": L(s["rock"]["side"]),
        }
        if "peak" in s:
            e["peak"] = gd_list([L(n) for n in s["peak"]["top"]]); e["peak_edge"] = L(s["peak"]["edge"])
        else:
            e["peak"] = gd_list([L(n) for n in ATLAS["groups"]["snow"]["top"]]); e["peak_edge"] = L("snow_edge")
        e["ice"] = L("ice_top")
        body = ", ".join(f'&"{k}": {v}' for k, v in e.items())
        out.append(f'\t&"{b}": {{{body}}},')
    out += ["}", "", "",
            "## Layer number of a texture name (-1 if unknown).",
            "static func layer(name: StringName) -> int:",
            "\treturn LAYER.get(name, -1)",
            ""]
    open(os.path.join(ROOT, "src", "core", "block_textures.gd"), "w").write("\n".join(out))


def item_icon_atlas_gd():
    out = [
        "class_name ItemIconAtlas",
        "## GENERATED by art/tools/export_game.py from art/icons/icon_atlas.json - do not edit by hand.",
        "## Hand-tuned 32 x 32 icons (art/tools/icongen.py). Items not listed fall back to the",
        "## icons drawn in code by ItemIcons.",
        "",
        'const PATH := "res://assets/icons/item_icons.png"',
        f"const SIZE := {ICONS['icon_size']}",
        "",
        "const CELLS := {",
    ]
    out += [f'\t&"{i}": Vector2i({m["cell"][0]}, {m["cell"][1]}),' for i, m in ICONS["items"].items()]
    out += ["}", ""]
    open(os.path.join(ROOT, "src", "ui", "item_icon_atlas.gd"), "w").write("\n".join(out))


def main():
    copy_with_import(os.path.join(ROOT, "art", "textures", "atlas_array.png"), os.path.join("assets", "textures", "block_textures.png"))
    copy_with_import(os.path.join(ROOT, "art", "icons", "icon_atlas.png"), os.path.join("assets", "icons", "item_icons.png"))
    block_textures_gd()
    item_icon_atlas_gd()
    open(os.path.join(ROOT, "art", ".gdignore"), "w").close()
    print("exported block textures, item icons and GDScript tables")


if __name__ == "__main__":
    main()
