extends Node
## Sound, music and ambience (Milestone 10).
##
## All audio files are generated by tools/gen_audio.py (no external samples):
##   res://assets/audio/sfx/<name>.wav         one-shots; name_0, name_1... are variations
##   res://assets/audio/ambience/<name>.ogg    seamless loops
##   res://assets/audio/music/<name>.ogg       looping tracks
##
## Buses: Master > Music, SFX, Ambience, UI (created here if the project has none).
## SFX plays through pooled players (2D for UI/player, 3D for world sounds) with
## random pitch, and a per-sound rate limit so a big fight never stacks 30 hits.
## The music director crossfades between tracks by context (menu, day, night,
## town, combat, dungeon, boss); the ambience mixer fades loop layers (wind,
## rain, birds, crickets, sea, cave, town, fire) towards target volumes that
## World/WeatherSystem set every frame.

const SFX_DIR := "res://assets/audio/sfx/"
const AMB_DIR := "res://assets/audio/ambience/"
const MUSIC_DIR := "res://assets/audio/music/"
const BUSES := [&"Music", &"SFX", &"Ambience", &"UI"]
const POOL_2D := 12
const POOL_3D := 28
const MUSIC_FADE := 2.5
## Linear volume per bus at 100% (the mix).
const BUS_MIX := {&"Music": 0.55, &"SFX": 0.9, &"Ambience": 0.7, &"UI": 0.7}

var music_track: StringName = &""
## Plays/queues counted for tests and the debug overlay.
var played := 0
var enabled := true

var _streams: Dictionary = {}  # path -> AudioStream (or null if missing)
var _variants: Dictionary = {}  # name -> Array[String] paths
var _pool2d: Array[AudioStreamPlayer] = []
var _pool3d: Array[AudioStreamPlayer3D] = []
var _next2d := 0
var _next3d := 0
var _last_play: Dictionary = {}  # name -> msec
var _music: Array[AudioStreamPlayer] = []
var _music_cur := 0
var _amb: Dictionary = {}  # name -> AudioStreamPlayer
var _amb_target: Dictionary = {}  # name -> linear 0..1
var _volumes: Dictionary = {&"Master": 1.0, &"Music": 1.0, &"SFX": 1.0, &"Ambience": 1.0, &"UI": 1.0}
var _reverb: AudioEffectReverb


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	_setup_buses()
	for i in POOL_2D:
		var p := AudioStreamPlayer.new()
		p.bus = &"SFX"
		add_child(p)
		_pool2d.append(p)
	for i in POOL_3D:
		var p := AudioStreamPlayer3D.new()
		p.bus = &"SFX"
		p.unit_size = 6.0
		p.max_distance = 45.0
		p.attenuation_model = AudioStreamPlayer3D.ATTENUATION_INVERSE_DISTANCE
		p.panning_strength = 0.8
		add_child(p)
		_pool3d.append(p)
	for i in 2:
		var m := AudioStreamPlayer.new()
		m.bus = &"Music"
		m.volume_db = -80.0
		add_child(m)
		_music.append(m)
	get_tree().node_added.connect(_on_node_added)
	_connect_events()


func _setup_buses() -> void:
	for b in BUSES:
		if AudioServer.get_bus_index(b) < 0:
			AudioServer.add_bus()
			var idx := AudioServer.bus_count - 1
			AudioServer.set_bus_name(idx, b)
			AudioServer.set_bus_send(idx, &"Master")
	# Caves echo: a reverb on SFX that World enables underground.
	var sfx := AudioServer.get_bus_index(&"SFX")
	_reverb = AudioEffectReverb.new()
	_reverb.room_size = 0.75
	_reverb.damping = 0.4
	_reverb.wet = 0.35
	AudioServer.add_bus_effect(sfx, _reverb)
	AudioServer.set_bus_effect_enabled(sfx, AudioServer.get_bus_effect_count(sfx) - 1, false)
	_apply_volumes()


## Volume of a bus, 0..1 (Settings menu).
func set_volume(bus: StringName, linear: float) -> void:
	_volumes[bus] = clampf(linear, 0.0, 1.0)
	_apply_volumes()


func get_volume(bus: StringName) -> float:
	return float(_volumes.get(bus, 1.0))


func _apply_volumes() -> void:
	for b in _volumes:
		var idx := AudioServer.get_bus_index(b)
		if idx < 0:
			continue
		var v: float = _volumes[b] * float(BUS_MIX.get(b, 1.0))
		AudioServer.set_bus_volume_db(idx, linear_to_db(maxf(v, 0.0001)))
		AudioServer.set_bus_mute(idx, v <= 0.001)


## Cave echo on world sounds.
func set_cave_reverb(on: bool) -> void:
	var sfx := AudioServer.get_bus_index(&"SFX")
	for i in AudioServer.get_bus_effect_count(sfx):
		if AudioServer.get_bus_effect(sfx, i) == _reverb:
			AudioServer.set_bus_effect_enabled(sfx, i, on)


# --- Library ---------------------------------------------------------------------------

func _load(path: String) -> AudioStream:
	if _streams.has(path):
		return _streams[path]
	var s: AudioStream = load(path) if ResourceLoader.exists(path) else null
	_streams[path] = s
	return s


## Paths of a sound: "swing" -> swing_0, swing_1, swing_2 (or just swing).
func _paths(sound: StringName) -> Array:
	if _variants.has(sound):
		return _variants[sound]
	var out := []
	var base := SFX_DIR + String(sound)
	if ResourceLoader.exists(base + ".wav"):
		out.append(base + ".wav")
	var k := 0
	while ResourceLoader.exists("%s_%d.wav" % [base, k]):
		out.append("%s_%d.wav" % [base, k])
		k += 1
	_variants[sound] = out
	return out


func has_sound(sound: StringName) -> bool:
	return not _paths(sound).is_empty()


func _pick(sound: StringName, min_gap_ms: int) -> AudioStream:
	if not enabled:
		return null
	var now := Time.get_ticks_msec()
	if now - int(_last_play.get(sound, -100000)) < min_gap_ms:
		return null
	var paths := _paths(sound)
	if paths.is_empty():
		return null
	_last_play[sound] = now
	played += 1
	return _load(paths[randi() % paths.size()])


# --- Playback --------------------------------------------------------------------------------

## Called with (sound, position or null) for every sound that plays - the
## accessibility layer shows captions through it (Milestone 13).
var caption_hook: Callable


## Non-positional sound (player actions, UI). Returns false if skipped.
func play(sound: StringName, volume_db: float = 0.0, pitch_jitter: float = 0.06, bus: StringName = &"SFX", min_gap_ms: int = 40) -> bool:
	var s := _pick(sound, min_gap_ms)
	if s == null:
		return false
	var p := _pool2d[_next2d]
	_next2d = (_next2d + 1) % _pool2d.size()
	p.stream = s
	p.bus = bus
	p.volume_db = volume_db
	p.pitch_scale = 1.0 + randf_range(-pitch_jitter, pitch_jitter)
	p.play()
	if caption_hook.is_valid() and bus != &"UI":
		caption_hook.call(sound, null)
	return true


func play_ui(sound: StringName, volume_db: float = 0.0) -> bool:
	return play(sound, volume_db, 0.03, &"UI", 30)


## Sound at a world position.
func play_at(sound: StringName, pos: Vector3, volume_db: float = 0.0, pitch_jitter: float = 0.08, max_distance: float = 45.0, min_gap_ms: int = 40) -> bool:
	var s := _pick(sound, min_gap_ms)
	if s == null:
		return false
	var p := _pool3d[_next3d]
	_next3d = (_next3d + 1) % _pool3d.size()
	p.stream = s
	p.global_position = pos
	p.volume_db = volume_db
	p.max_distance = max_distance
	p.pitch_scale = 1.0 + randf_range(-pitch_jitter, pitch_jitter)
	p.play()
	if caption_hook.is_valid():
		caption_hook.call(sound, pos)
	return true


# --- Music -------------------------------------------------------------------------------------

## Crossfades to `track` ("" = silence). Same track again does nothing.
func set_music(track: StringName) -> void:
	if track == music_track:
		return
	music_track = track
	var old := _music[_music_cur]
	_music_cur = 1 - _music_cur
	var nxt := _music[_music_cur]
	var tw := create_tween()
	tw.set_parallel(true)
	tw.tween_property(old, "volume_db", -80.0, MUSIC_FADE).set_trans(Tween.TRANS_SINE)
	if track != &"" and enabled:
		var s := _load(MUSIC_DIR + String(track) + ".ogg")
		if s:
			if s is AudioStreamOggVorbis:
				(s as AudioStreamOggVorbis).loop = true
			nxt.stream = s
			nxt.volume_db = -40.0
			nxt.play()
			tw.tween_property(nxt, "volume_db", 0.0, MUSIC_FADE).set_trans(Tween.TRANS_SINE)
	tw.chain().tween_callback(func() -> void:
		if old.volume_db <= -79.0:
			old.stop())


## Picks the track for the moment (World calls this about once a second).
static func pick_music(ctx: Dictionary) -> StringName:
	if ctx.get("menu", false):
		return &"menu"
	if ctx.get("boss", false):
		return &"boss"
	if ctx.get("combat", false):
		return &"combat"
	if ctx.get("dungeon", false) or ctx.get("underground", false):
		return &"dungeon"
	if ctx.get("town", false):
		return &"town"
	if ctx.get("night", false):
		return &"explore_night"
	return &"explore_day"


# --- Ambience ----------------------------------------------------------------------------------

## Target volume (0..1) of an ambience loop; it fades there smoothly.
func set_ambience(layer: StringName, volume: float) -> void:
	_amb_target[layer] = clampf(volume, 0.0, 1.0)


func ambience_volume(layer: StringName) -> float:
	var p: AudioStreamPlayer = _amb.get(layer)
	return db_to_linear(p.volume_db) if p and p.playing else 0.0


func clear_ambience() -> void:
	for k in _amb_target.keys():
		_amb_target[k] = 0.0


func _process(delta: float) -> void:
	for layer: StringName in _amb_target:
		var target: float = _amb_target[layer] if enabled else 0.0
		var p: AudioStreamPlayer = _amb.get(layer)
		if p == null:
			if target <= 0.001:
				continue
			var s := _load(AMB_DIR + String(layer) + ".ogg")
			if s == null:
				_amb_target[layer] = 0.0
				continue
			if s is AudioStreamOggVorbis:
				(s as AudioStreamOggVorbis).loop = true
			p = AudioStreamPlayer.new()
			p.bus = &"Ambience"
			p.stream = s
			p.volume_db = -60.0
			add_child(p)
			_amb[layer] = p
		var cur := db_to_linear(p.volume_db) if p.playing else 0.0
		var v := move_toward(cur, target, delta * 0.5)
		if v <= 0.002:
			if p.playing:
				p.stop()
			continue
		if not p.playing:
			p.play(randf() * maxf(0.1, p.stream.get_length() - 0.5))
		p.volume_db = linear_to_db(v)


# --- Hooks -------------------------------------------------------------------------------------

## Every button in the game clicks.
func _on_node_added(node: Node) -> void:
	if node is BaseButton and not node.has_meta(&"silent"):
		(node as BaseButton).pressed.connect(func() -> void: play_ui(&"ui_click", -6.0))


func _connect_events() -> void:
	Events.damage_dealt.connect(func(pos: Vector3, _amount: float, crit: bool, to_player: bool, _tag: String) -> void:
		if to_player:
			play(&"hurt", -2.0)
		else:
			play_at(&"hit_crit" if crit else &"hit_flesh", pos, 0.0 if crit else -3.0))
	Events.enemy_killed.connect(func(_e: Node, id: StringName, pos: Vector3) -> void:
		play_at(&"bones" if String(id).contains("skeleton") or String(id).contains("bone") else &"enemy_die", pos, -2.0))
	Events.item_picked_up.connect(func(_id: StringName, _n: int) -> void: play(&"pickup", -8.0, 0.1, &"SFX", 90))
	Events.level_up.connect(func(_l: int) -> void: play_ui(&"level_up", 0.0))
	Events.biome_discovered.connect(func(_id: StringName) -> void: play_ui(&"discover", -3.0))
	Events.poi_discovered.connect(func(_id: String) -> void: play_ui(&"discover", -3.0))
	Events.place_discovered.connect(func(_k: String) -> void: play_ui(&"discover", -5.0))
	Events.recipe_learned.connect(func(_r: StringName) -> void: play_ui(&"learn", -4.0))
	Events.spell_learned.connect(func(_s: StringName) -> void: play_ui(&"learn", -2.0))
	Events.item_crafted.connect(func(_i: StringName, _n: int) -> void: play(&"craft", -5.0, 0.04, &"SFX", 150))
	Events.open_container.connect(func(_c: Node) -> void: play(&"chest_open", -4.0))
	Events.raid_warning.connect(func(_t: String, _p: Vector3, _s: float) -> void: play_ui(&"horn", 0.0))
	Events.boss_started.connect(func(b: Node) -> void:
		if b is Node3D:
			play_at(&"boss_roar", (b as Node3D).global_position, 4.0, 0.03, 90.0))
	Events.world_event_started.connect(func(_id: StringName) -> void: play_ui(&"warning", -4.0))
	Events.trade_done.connect(func(_s: String, _c: int) -> void: play_ui(&"coin", -4.0))
	Events.player_died.connect(func() -> void: play(&"enemy_die", 0.0, 0.0))
	Events.ability_used.connect(func(id: StringName) -> void: play(ability_sound(id), -3.0))


## Sound of a spell or class ability, by what its id says it does.
static func ability_sound(id: StringName) -> StringName:
	var s := String(id)
	for pair in [["fire", &"fire"], ["meteor", &"explosion"], ["frost", &"frost"], ["blizzard", &"frost"], ["ice", &"frost"],
			["storm", &"zap"], ["lightning", &"zap"], ["shock", &"zap"], ["heal", &"heal"], ["barrier", &"shield"],
			["iron_skin", &"shield"], ["blink", &"teleport"], ["vanish", &"teleport"], ["poison", &"poison"],
			["miasma", &"poison"], ["cry", &"horn"], ["rage", &"monster_growl"], ["whirl", &"swing_heavy"],
			["charge", &"swing_heavy"], ["missile", &"cast"]]:
		if s.contains(pair[0]):
			return pair[1]
	return &"cast"
