extends Node
## Balance report (Milestone 12): writes docs/BALANCE.md from BalanceModel -
## the same numbers the balance tests enforce.
##
##   godot --headless --path . res://tools/balance_report.tscn [-- --out=docs/BALANCE.md]

## Crafting level for the value table: materials ×1.0 (a trained crafter).
const CRAFTING_REF := 75

var _out := "res://docs/BALANCE.md"


func _ready() -> void:
	for a in OS.get_cmdline_user_args():
		if a.begins_with("--out="):
			_out = a.substr(6)
	var md := PackedStringArray()
	md.append("# Balance report")
	md.append("")
	md.append("Generated by `tools/balance_report.tscn` from the game's data and formulas (`BalanceModel`).")
	md.append("The balance tests (`test_m12_balance`) enforce the limits listed here. Model: a typical build")
	md.append("per class (skill points by plan), the best gear the level allows, its weapon moveset, fighting a")
	md.append("level-appropriate Skeleton Warrior scaled by dungeon rank, without dodging, blocking or abilities")
	md.append("(except the Wizard's Firebolt, mana-limited over 30 s).")
	md.append("")
	_classes(md)
	_xp(md)
	_crafting(md)
	_economy(md)
	var f := FileAccess.open(_out, FileAccess.WRITE)
	f.store_string("\n".join(md) + "\n")
	f.close()
	print("balance report written to ", ProjectSettings.globalize_path(_out))
	get_tree().quit()


func _classes(md: PackedStringArray) -> void:
	md.append("## Classes")
	md.append("")
	md.append("Builds: " + ", ".join(BalanceModel.CLASSES.map(func(c: StringName) -> String:
		var parts := PackedStringArray()
		var b: Dictionary = BalanceModel.BUILDS[c]
		for s in b:
			parts.append("%s %d%%" % [Skill.NAMES[s], roundi(float(b[s]) * 100.0)])
		return "**%s** (%s)" % [String(c).capitalize(), ", ".join(parts)])) + ".")
	md.append("")
	md.append("| Level | Enemy (rank, HP, DPS) | Class | Weapon | HP | Dmg red. | DPS | Time to kill | Time to die | Ratio |")
	md.append("|---:|---|---|---|---:|---:|---:|---:|---:|---:|")
	for lvl in BalanceModel.LEVELS:
		for c in BalanceModel.CLASSES:
			var d := BalanceModel.duel(c, lvl)
			var s: Dictionary = d.char
			var e: Dictionary = d.enemy
			md.append("| %d | %s, %d, %.1f | %s | %s | %d | %d%% | %.1f | %.1f s | %.1f s | %.1f |" % [lvl,
				PoiInfo.RANKS[e.rank], e.hp, e.dps, String(c).capitalize(), s.weapon, s.hp, roundi(s.dr * 100.0), s.dps,
				d.ttk, d.ttd, d.ratio])
	md.append("")
	md.append("Physical damage multiplier at 100 Strength: " + ", ".join(BalanceModel.CLASSES.map(func(c: StringName) -> String:
		return "%s ×%.2f" % [String(c).capitalize(), BalanceModel.max_strength_phys(c)])) + " (a Wizard never matches a Knight or Barbarian).")
	md.append("")


func _xp(md: PackedStringArray) -> void:
	md.append("## Experience pacing")
	md.append("")
	md.append("Fighting level-appropriate monsters (kill time + 25 s to find the next), plus 25% from")
	md.append("harvesting, crafting and discoveries.")
	md.append("")
	md.append("| Level | XP to next | Minutes for this level | Hours from level 1 |")
	md.append("|---:|---:|---:|---:|")
	for lvl in [2, 5, 10, 15, 20, 25, 30, 40, 50, 60, 75, 90, 99]:
		md.append("| %d | %d | %.0f | %.1f |" % [lvl, Progression.xp_to_next(lvl), BalanceModel.minutes_per_level(lvl),
			BalanceModel.hours_to_level(lvl)])
	md.append("")


func _crafting(md: PackedStringArray) -> void:
	md.append("## Crafting value")
	md.append("")
	md.append("Base value of the result ÷ base value of the materials at Crafting %d (materials ×%.2f)." % [CRAFTING_REF, Skill.material_cost_mult(CRAFTING_REF)])
	md.append("Processing (ingots, leather, planks) and gear should add value; Legendary recipes need a scroll")
	md.append("and materials from S-rank content, so they are worth far more than their inputs.")
	md.append("")
	md.append("| Recipe | Station | Inputs | Output | Ratio | Shop money machine? |")
	md.append("|---|---|---:|---:|---:|---|")
	var ids := RecipeBook.all().keys()
	ids.sort()
	for id in ids:
		var r: RecipeData = RecipeBook.all()[id]
		var v := BalanceModel.recipe_value(r, CRAFTING_REF)
		var arb := BalanceModel.craft_arbitrage(r)
		md.append("| %s | %s | %d | %d | %.2f | %s |" % [id, r.station_name(), v.input, v.output, v.ratio,
			"materials not sold" if arb == 0.0 else ("**yes (%.2f)**" % arb if arb >= 1.0 else "no (%.2f)" % arb)])
	md.append("")


func _economy(md: PackedStringArray) -> void:
	md.append("## Economy")
	md.append("")
	md.append("- Shops sell at ×%.2f of base value and buy at ×%.2f (before region, reputation and saturation)." % [Economy.BUY_MARKUP, Economy.SELL_RATE])
	md.append("- Best town-to-town trade (cheapest region + best reputation → dearest region + kingdom + best")
	md.append("  reputation): **×%.2f** of the money spent - trading never makes money on its own." % BalanceModel.trade_arbitrage())
	md.append("- Selling the same item repeatedly saturates a shop (−%d%% per item, down to ×%.1f)." % [roundi(Economy.SATURATION_STEP * 100.0), Economy.MIN_SATURATION])
	md.append("")
