#!/usr/bin/env python3
"""Builds the external blueprint designer (Milestone 8).

Reads the game's own data (build pieces, item names, built-in blueprints) and
inlines it as a catalog into web/blueprint-designer/designer.src.html, writing:

  web/blueprint-designer/index.html   standalone page (open it in any browser)
  <out>/designer_artifact.html        the same page without the document
                                      skeleton (for publishing as an Artifact)

Run after changing build pieces:  python3 tools/build_designer.py [artifact_out_dir]
"""
import json, os, re, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
CATEGORIES = ["Floors", "Walls", "Doors", "Windows", "Fences", "Roofs", "Furniture", "Storage",
              "Stations", "Defenses", "Lights", "Claims", "Farming"]
PLACEMENT = ["floor", "object", "edge", "roof"]


def tres_fields(path):
    text = open(path).read()
    res = text[text.index("[resource]"):]
    out = {}
    for m in re.finditer(r'^(\w+) = (.*?)(?=^\w+ = |\Z)', res, re.S | re.M):
        out[m.group(1)] = m.group(2).strip()
    return out


def sval(v):
    v = v.strip()
    if v.startswith('&"') or v.startswith('"'):
        return v.split('"')[1]
    return v


def dict_val(v):
    return {k: int(n) for k, n in re.findall(r'&"(\w+)":\s*(\d+)', v)}


def piece_hp(cat, cost, explicit):
    if explicit > 0:
        return explicit
    hp = 200.0
    if any(k in cost for k in ("iron_ingot", "copper_ingot", "mithril_ingot")):
        hp = 800.0
    elif "stone" in cost:
        hp = 500.0
    if cat in (6, 7, 8, 10, 12):
        hp *= 0.5
    elif cat in (0, 5):
        hp *= 0.8
    return hp


def catalog():
    pieces = []
    pdir = os.path.join(ROOT, "data/build_pieces")
    for f in sorted(os.listdir(pdir)):
        if not f.endswith(".tres"):
            continue
        d = tres_fields(os.path.join(pdir, f))
        cat = int(d.get("category", "1"))
        cost = dict_val(d.get("cost", "{}"))
        pieces.append({
            "id": sval(d["id"]), "name": sval(d.get("display_name", d["id"])),
            "description": sval(d.get("description", '""')),
            "category": CATEGORIES[cat], "cat": cat,
            "slot": PLACEMENT[int(d.get("placement", "2"))],
            "behavior": int(d.get("behavior", "0")),
            "cost": cost, "level": int(d.get("required_level", "1")),
            "hp": piece_hp(cat, cost, float(d.get("max_health", "0"))),
        })
    items = {}
    idir = os.path.join(ROOT, "data/items")
    for f in os.listdir(idir):
        if f.endswith(".tres"):
            d = tres_fields(os.path.join(idir, f))
            items[sval(d["id"])] = sval(d.get("display_name", d["id"]))
    examples = []
    bdir = os.path.join(ROOT, "data/blueprints")
    for f in sorted(os.listdir(bdir)):
        if f.endswith(".json"):
            examples.append(json.load(open(os.path.join(bdir, f))))
    return {"pieces": pieces, "items": items, "examples": examples, "format": "shardlands-blueprint", "version": 1}


def main():
    src = open(os.path.join(ROOT, "web/blueprint-designer/designer.src.html")).read()
    cat = json.dumps(catalog(), separators=(",", ":"))
    body = src.replace("/*CATALOG*/null", cat)
    standalone = ("<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n"
                  "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, viewport-fit=cover\">\n"
                  "<!-- Generated by tools/build_designer.py from designer.src.html - edit that file. -->\n"
                  "</head>\n<body>\n" + body.replace("/*STANDALONE*/false", "true") + "\n</body>\n</html>\n")
    open(os.path.join(ROOT, "web/blueprint-designer/index.html"), "w").write(standalone)
    if len(sys.argv) > 1:
        os.makedirs(sys.argv[1], exist_ok=True)
        # The artifact viewer can't hand out files: drop the download button and its code there.
        art = re.sub(r"/\*DL-START\*/.*?/\*DL-END\*/", "", body, flags=re.S)
        art = re.sub(r"<!--DL-->.*?\n", "", art)
        open(os.path.join(sys.argv[1], "designer_artifact.html"), "w").write(art)
    print("designer built:", len(json.loads(cat)["pieces"]), "pieces")


if __name__ == "__main__":
    main()
