extends SceneTree
## Regenerates docs/XP_TABLE.md and docs/CLASSES_AND_SKILLS.md from the live
## formulas and class data, so documentation never drifts from the game.
##   godot --headless --path . -s tools/gen_rpg_tables.gd


func _initialize() -> void:
	_xp_table()
	_classes_and_skills()
	print("RPG tables written")
	quit()


func _xp_table() -> void:
	var lines := PackedStringArray()
	lines.append("# XP table (levels 1–100)")
	lines.append("")
	lines.append("Generated by `tools/gen_rpg_tables.gd` from `src/rpg/progression.gd` — do not edit by hand.")
	lines.append("")
	lines.append("XP to next level = `100 + 40·(L−1)^1.5 + 0.35·(L−1)^3` (rounded to 10). Each level gives %d skill points, +1 bonus every %d levels. Level-ups fully restore health and mana." % [Progression.SKILL_POINTS_PER_LEVEL, Progression.BONUS_POINT_EVERY])
	lines.append("")
	lines.append("XP sources today: combat (enemy XP × level-difference factor: up to +50% vs stronger foes, down to 10% vs trivial ones), discovering a biome (60), discovering a cave (40), harvesting/gathering (1–6), cooking (4). Boss, dungeon, quest, trading and farming XP hooks exist (`Progression.Source`) for later milestones.")
	lines.append("")
	lines.append("| Level | XP required (to next) | Total XP to reach | Unlocks at this level |")
	lines.append("|---:|---:|---:|---|")
	var abilities := {}
	for c in ClassRegistry.all():
		for a in c.abilities:
			if not abilities.has(a.unlock_level):
				abilities[a.unlock_level] = []
			abilities[a.unlock_level].append("%s: %s" % [c.display_name, a.display_name])
	for l in range(1, 101):
		var unlocks := PackedStringArray()
		if l > 1:
			unlocks.append("+%d skill points" % Progression.skill_points_for_level(l))
		if abilities.has(l):
			unlocks.append("Abilities — " + ", ".join(abilities[l]))
		if Progression.GEAR_TIER_LEVELS.has(l):
			unlocks.append(Progression.GEAR_TIER_LEVELS[l])
		if l == 100:
			unlocks.append("Maximum level")
		lines.append("| %d | %s | %s | %s |" % [l, _num(Progression.xp_to_next(l)) if l < 100 else "—",
			_num(Progression.total_xp_for(l)), "; ".join(unlocks)])
	lines.append("")
	lines.append("Total skill points earned by level 100: %d (plus 50 starting points). Five skills × 100 = 500, so no character can master everything." % Progression.total_skill_points_at(100))
	_write("res://docs/XP_TABLE.md", lines)


func _classes_and_skills() -> void:
	var lines := PackedStringArray()
	lines.append("# Classes and skills")
	lines.append("")
	lines.append("Generated by `tools/gen_rpg_tables.gd` from `data/classes/*.tres` and `src/rpg/skill.gd` — do not edit by hand.")
	lines.append("")
	lines.append("## Starting skills (exactly 50 points each)")
	lines.append("")
	lines.append("| Class | Strength | Mana Control | Defense | Crafting | Dexterity | Health | Mana | Temperature Shield |")
	lines.append("|---|---:|---:|---:|---:|---:|---:|---:|---|")
	for c in ClassRegistry.all():
		var row := "| **%s** |" % c.display_name
		for s in Skill.ALL:
			row += " %d |" % c.starting_skill(s)
		var req := c.temperature_shield_requirement()
		row += " %d | %d | MC %d, %d mana |" % [roundi(Skill.max_health(c.starting_skill(Skill.DEFENSE), c.base_health, c.health_per_defense)),
			roundi(Skill.max_mana(c.starting_skill(Skill.MANA_CONTROL), c.base_mana, c.mana_per_point)),
			req, roundi(c.temperature_shield_cost * Skill.mana_cost_mult(req))]
		lines.append(row)
	lines.append("")
	for c in ClassRegistry.all():
		lines.append("### %s — %s" % [c.display_name, c.role_summary])
		lines.append("")
		lines.append(c.description)
		lines.append("")
		var prof := PackedStringArray()
		for w in c.weapon_proficiency:
			prof.append("%s ×%.2f" % [String(w), float(c.weapon_proficiency[w])])
		lines.append("- Weapons: %s (others ×%.2f)" % [", ".join(prof), c.unskilled_weapon_mult])
		lines.append("- Class power: physical ×%.2f, spells ×%.2f · block %d%% · parry %.2fs · backstab ×%.1f%s" % [
			c.physical_power, c.spell_power, roundi(c.block_reduction * 100), c.parry_window, c.backstab_multiplier,
			" · Rage" if c.uses_rage else ""])
		var eff := PackedStringArray()
		for s in Skill.ALL:
			eff.append("%s ×%.2f" % [Skill.NAMES[s], c.efficiency(s)])
		lines.append("- Skill efficiency: " + ", ".join(eff))
		for a in c.abilities:
			lines.append("- **Lv %d – %s** (%s %d, %ss cooldown): %s" % [a.unlock_level, a.display_name, a.cost_name(),
				roundi(a.cost), a.cooldown, a.description])
		lines.append("")
	lines.append("## Skill progression (values at skill level, per class)")
	lines.append("")
	var levels := [1, 10, 25, 50, 75, 100]
	for s in Skill.ALL:
		lines.append("### %s" % Skill.NAMES[s])
		lines.append("")
		lines.append(Skill.DESCRIPTIONS[s])
		lines.append("")
		var header := "| Class |"
		var sep := "|---|"
		for l in levels:
			header += " %d |" % l
			sep += "---|"
		lines.append(header)
		lines.append(sep)
		for c in ClassRegistry.all():
			var row := "| %s |" % c.display_name
			for l in levels:
				row += " %s |" % _skill_value(s, l, c)
			lines.append(row)
		lines.append("")
		lines.append("Milestones: " + "; ".join(Skill.PERKS[s].map(func(p: Array) -> String: return "**%d %s** – %s" % [p[0], p[1], p[2]])))
		lines.append("")
	_write("res://docs/CLASSES_AND_SKILLS.md", lines)


func _skill_value(s: StringName, l: int, c: ClassData) -> String:
	var e := c.efficiency(s)
	match s:
		Skill.STRENGTH:
			return "dmg ×%.2f" % Skill.physical_damage_mult(l, e, c.physical_power)
		Skill.MANA_CONTROL:
			return "%d mana, spells ×%.2f" % [roundi(Skill.max_mana(l, c.base_mana, c.mana_per_point)), Skill.spell_power_mult(l, e, c.spell_power)]
		Skill.DEFENSE:
			var armor := c.base_armor + Skill.skill_armor(l, e)
			return "%d HP, −%d%% dmg" % [roundi(Skill.max_health(l, c.base_health, c.health_per_defense)), roundi(Skill.damage_reduction(armor) * 100)]
		Skill.CRAFTING:
			return "mats ×%.2f, +%d%% yield" % [Skill.material_cost_mult(l), roundi(Skill.harvest_bonus_chance(l, e) * 100)]
		Skill.DEXTERITY:
			return "spd ×%.2f, crit %d%%" % [Skill.attack_speed_mult(l, e), roundi((Skill.crit_chance(l, e) + c.crit_bonus) * 100)]
	return ""


func _num(n: int) -> String:
	var s := str(n)
	var out := ""
	var k := 0
	for i in range(s.length() - 1, -1, -1):
		out = s[i] + out
		k += 1
		if k % 3 == 0 and i > 0:
			out = "," + out
	return out


func _write(path: String, lines: PackedStringArray) -> void:
	var f := FileAccess.open(path, FileAccess.WRITE)
	f.store_string("\n".join(lines) + "\n")
	f.close()
