extends Node
## World-generation stress test + performance benchmark (Milestone 12).
## Writes docs/PERFORMANCE.md from tests/stress.gd - the same code the test
## suite uses for its budgets.
##
##   godot --headless --path . res://tools/stress_test.tscn [-- --seeds=20 --chunks=24 --out=docs/PERFORMANCE.md]
##
## Run without --headless to include rendering in the frame times.

var _out := "res://docs/PERFORMANCE.md"
var _seeds := 20
var _chunks := 24


func _ready() -> void:
	for a in OS.get_cmdline_user_args():
		if a.begins_with("--out="):
			_out = a.substr(6)
		elif a.begins_with("--seeds="):
			_seeds = maxi(1, a.substr(8).to_int())
		elif a.begins_with("--chunks="):
			_chunks = maxi(4, a.substr(9).to_int())
	var md := PackedStringArray()
	md.append("# Performance and stress testing")
	md.append("")
	md.append("Generated by `tools/stress_test.tscn` (Milestone 12) on %s, Godot %s, %s, %d CPU threads%s." % [
		Time.get_date_string_from_system(), Engine.get_version_info().string, OS.get_name(), OS.get_processor_count(),
		" (headless: CPU only, no rendering)" if DisplayServer.get_name() == "headless" else ""])
	md.append("The test suite enforces the budgets below (`test_m12_worldgen_stress`, `test_m12_performance`).")
	md.append("")
	_worldgen(md)
	await _bench(md)
	var f := FileAccess.open(_out, FileAccess.WRITE)
	f.store_string("\n".join(md) + "\n")
	f.close()
	print("written ", ProjectSettings.globalize_path(_out))
	get_tree().quit()


func _worldgen(md: PackedStringArray) -> void:
	md.append("## World generation across %d seeds" % _seeds)
	md.append("")
	md.append("Each seed: find the spawn, check towns and points of interest a new player can reach, generate %d" % _chunks)
	md.append("chunks (around spawn, random far points, the world edge, caves) and validate every mesh, regenerate")
	md.append("a chunk with a second generator (determinism), and lay out every floor of up to 4 nearby dungeons.")
	md.append("")
	md.append("| Seed | Spawn | Biome | Towns ≤2 km | Nearest town | POIs ≤2.5 km | Dungeon floors | Chunk avg / max | Problems |")
	md.append("|---:|---|---|---:|---:|---:|---:|---:|---|")
	var rng := RandomNumberGenerator.new()
	rng.seed = 12345
	var problems := 0
	var worst_chunk := 0.0
	var sum_chunk := 0.0
	for i in _seeds:
		var s := GameState.DEFAULT_SEED if i == 0 else rng.randi()
		var r := Stress.worldgen_seed(s, _chunks)
		problems += (r.errors as PackedStringArray).size()
		worst_chunk = maxf(worst_chunk, r.chunk_max_ms)
		sum_chunk += r.chunk_avg_ms
		md.append("| %d | %d, %d (%d m) | %s | %d | %d m | %d | %d | %.1f / %.1f ms | %s |" % [s, r.spawn.x, r.spawn.y, roundi(r.spawn_dist),
			r.spawn_biome, r.towns_2km, roundi(minf(r.nearest_town, 99999.0)), r.pois_2_5km, r.dungeon_floors, r.chunk_avg_ms, r.chunk_max_ms,
			"none" if (r.errors as PackedStringArray).is_empty() else "; ".join(r.errors)])
		print("seed %d: %d problems" % [s, (r.errors as PackedStringArray).size()])
	md.append("")
	md.append("**%d problems** over %d seeds. LOD0 chunk generation: %.1f ms average, %.1f ms worst (budget %.0f ms;" % [
		problems, _seeds, sum_chunk / _seeds, worst_chunk, Stress.BUDGET_CHUNK_MS])
	md.append("generation runs on worker threads, so this is latency, not frame time).")
	md.append("")


func _bench(md: PackedStringArray) -> void:
	SaveManager.start_transient(GameState.DEFAULT_SEED, &"knight")
	var world := (load("res://scenes/main.tscn") as PackedScene).instantiate() as World
	add_child(world)
	var waited := 0
	while not world.is_ready and waited < 1500:
		await get_tree().process_frame
		waited += 1
	var b: Dictionary = await Stress.benchmark(get_tree(), world, 1.0)
	md.append("## In-game frame times")
	md.append("")
	md.append("Main scene, knight at the default spawn, view distance from the default settings. Budgets: average")
	md.append("≤ %.1f ms (60 fps), 95th percentile ≤ %.1f ms (30 fps); streaming hitches ≤ %.0f ms." % [Stress.BUDGET_AVG_MS, Stress.BUDGET_P95_MS, Stress.BUDGET_STREAM_SPIKE_MS])
	md.append("")
	md.append("| Scenario | Load | Average | 95th pct | Worst |")
	md.append("|---|---|---:|---:|---:|")
	md.append(_row("Idle (exploring)", "%d nodes" % int(b.idle.nodes), b.idle))
	md.append(_row("Monster crowd, AI on", "%d monsters" % int(b.enemies.count), b.enemies))
	md.append(_row("Large base", "%d building pieces" % int(b.buildings.count), b.buildings))
	md.append(_row("Particle bursts", "3 bursts / frame", b.particles))
	md.append(_row("Streaming (4 × 700 m jumps)", "near area ready ≤ %.1f s" % float(b.streaming.ready_s), b.streaming))
	md.append("")
	md.append("Static memory after the run: %.0f MB." % float(b.memory_mb))
	md.append("")
	md.append("Notes: chunk meshes are built on worker threads and committed under a per-frame budget")
	md.append("(`ChunkManager`), so streaming shows up as a few longer frames, not stalls. Far terrain is")
	md.append("cached LOD tiles. Monsters only probe for stair steps when last tick's movement hit terrain or a")
	md.append("building, not another character (crowds used to cost ~0.2 ms per monster per tick).")
	md.append("The browser build has no worker threads: there the streamer runs one generation job per frame")
	md.append("(~6 ms), skips prefetching and keeps a smaller detail ring, so walking costs short hitches")
	md.append("instead of long stalls (Milestone 13).")
	world.queue_free()
	await get_tree().process_frame


func _row(name: String, load_text: String, s: Dictionary) -> String:
	return "| %s | %s | %.1f ms | %.1f ms | %.1f ms |" % [name, load_text, float(s.avg), float(s.p95), float(s.max)]
