extends Node
## World survey + generation benchmark (Milestone 9).
##
## Samples the whole 3,003,289-chunk world for one seed - biomes, land/sea,
## heights, every settlement and point of interest - and benchmarks chunk
## generation, so changes to world generation can be checked at full scale.
##
##   godot --headless --path . res://tools/world_survey.tscn -- [--seed=N] [--out=docs/WORLD_SURVEY.md] [--step=8]
##
## --step: sample spacing in chunks (8 = 47,089 columns over the world).

var _out := "res://docs/WORLD_SURVEY.md"
var _step := 8


func _ready() -> void:
	for a in OS.get_cmdline_user_args():
		if a.begins_with("--out="):
			_out = a.substr(6)
		elif a.begins_with("--step="):
			_step = maxi(1, a.substr(7).to_int())
	var gen := TerrainGenerator.new(GameState.world_seed, load("res://data/worldgen/default_worldgen.tres"))
	var md := PackedStringArray()
	md.append("# World survey")
	md.append("")
	md.append("Generated by `tools/world_survey.tscn` (Milestone 9). Seed **%d**, %s." % [GameState.world_seed,
		Time.get_datetime_string_from_system(false, true)])
	md.append("Re-run after changing world generation: `godot --headless --path . res://tools/world_survey.tscn -- --seed=N`.")
	md.append("")
	md.append("## Size")
	md.append("")
	var r := TerrainGenerator.WORLD_RADIUS_CHUNKS
	var span_km := (2 * r + 1) * TerrainGenerator.CHUNK_SIZE / 1000.0
	md.append("| | |")
	md.append("|---|---|")
	md.append("| Chunks | %d x %d = **%s** (target 3,000,000) |" % [2 * r + 1, 2 * r + 1, _thousands(TerrainGenerator.WORLD_CHUNK_COUNT)])
	md.append("| Chunk | %d x %d m, %d x %d block columns |" % [16, 16, 16, 16])
	md.append("| Extent | %.1f x %.1f km (%s km²), +-%d m from the origin |" % [span_km, span_km, _thousands(roundi(span_km * span_km)), TerrainGenerator.WORLD_LIMIT_M])
	md.append("| Columns | %s |" % _thousands(TerrainGenerator.WORLD_CHUNK_COUNT * 256))
	md.append("| Edge | land sinks into ocean from %d m, players stop at %d m |" % [TerrainGenerator.WORLD_EDGE_START_M, TerrainGenerator.WORLD_LIMIT_M])
	md.append("")

	# --- Terrain sample over the whole world ----------------------------------------------
	var t0 := Time.get_ticks_msec()
	var counts := {}
	var land := 0
	var n := 0
	var hmin := 1 << 30
	var hmax := -(1 << 30)
	var bands := [0, 0, 0, 0, 0, 0]  # <-10, -10..0, 0..10, 10..30, 30..60, >=60 blocks
	for cz in range(-r, r + 1, _step):
		for cx in range(-r, r + 1, _step):
			var smp := gen.sample_column(cx * 16 + 8, cz * 16 + 8)
			var h := TerrainGenerator.unpack_height(smp)
			var b := TerrainGenerator.unpack_biome(smp)
			counts[b] = int(counts.get(b, 0)) + 1
			n += 1
			if h >= TerrainGenerator.SEA_LEVEL:
				land += 1
			hmin = mini(hmin, h)
			hmax = maxi(hmax, h)
			bands[0 if h < -10 else 1 if h < 0 else 2 if h < 10 else 3 if h < 30 else 4 if h < 60 else 5] += 1
	var sample_s := (Time.get_ticks_msec() - t0) / 1000.0
	md.append("## Terrain (%s columns, every %d chunks, %.1f s)" % [_thousands(n), _step, sample_s])
	md.append("")
	md.append("Land %.1f%% · sea %.1f%% · heights %.1f m to %.1f m." % [100.0 * land / n, 100.0 - 100.0 * land / n,
		hmin * TerrainGenerator.BLOCK_HEIGHT, hmax * TerrainGenerator.BLOCK_HEIGHT])
	md.append("")
	md.append("| Biome | Share | Area (est.) |")
	md.append("|---|---:|---:|")
	var ids := counts.keys()
	ids.sort_custom(func(a: int, b: int) -> bool: return counts[a] > counts[b])
	for b: int in ids:
		var share := float(counts[b]) / n
		md.append("| %s | %.1f%% | %s km² |" % [gen.biomes[b].display_name if gen.biomes[b].display_name != "" else String(gen.biomes[b].id),
			share * 100.0, _thousands(roundi(share * span_km * span_km))])
	md.append("")
	md.append("| Height (m) | < -5 | -5..0 | 0..5 | 5..15 | 15..30 | >= 30 |")
	md.append("|---|---:|---:|---:|---:|---:|---:|")
	var row := "| Share |"
	for v in bands:
		row += " %.1f%% |" % (100.0 * v / n)
	md.append(row)
	md.append("")

	# --- Settlements and POIs over the whole world ---------------------------------------
	t0 = Time.get_ticks_msec()
	var lim := TerrainGenerator.WORLD_LIMIT_M
	var villages := 0
	var kingdoms := 0
	var r0 := Settlements.region_of(-lim, -lim)
	var r1 := Settlements.region_of(lim, lim)
	for rz in range(r0.y, r1.y + 1):
		for rx in range(r0.x, r1.x + 1):
			var st := gen.settlements.get_region(Vector2i(rx, rz))
			if st == null or absi(st.center.x) > lim or absi(st.center.y) > lim:
				continue
			if st.is_kingdom():
				kingdoms += 1
			else:
				villages += 1
	var set_s := (Time.get_ticks_msec() - t0) / 1000.0
	t0 = Time.get_ticks_msec()
	var kinds := [0, 0, 0, 0, 0]
	var ranks := [0, 0, 0, 0, 0, 0]
	var c0 := Exploration.cell_of(-lim, -lim)
	var c1 := Exploration.cell_of(lim, lim)
	for cz in range(c0.y, c1.y + 1):
		for cx in range(c0.x, c1.x + 1):
			var p := gen.pois.get_cell(Vector2i(cx, cz))
			if p == null:
				continue
			kinds[p.kind] += 1
			ranks[p.rank] += 1
	var poi_s := (Time.get_ticks_msec() - t0) / 1000.0
	md.append("## Places (every region of the world)")
	md.append("")
	md.append("- **%d kingdom capitals** and **%d villages** (%d regions of %d m, %.1f s)." % [kingdoms, villages,
		(r1.x - r0.x + 1) * (r1.y - r0.y + 1), Settlements.REGION, set_s])
	var poi_total := 0
	for v in kinds:
		poi_total += v
	var kparts := PackedStringArray()
	for k in kinds.size():
		kparts.append("%s %d" % [PoiInfo.KIND_NAMES[k], kinds[k]])
	md.append("- **%d points of interest** (%.1f s): %s." % [poi_total, poi_s, ", ".join(kparts)])
	var rparts := PackedStringArray()
	for k in ranks.size():
		rparts.append("%s %d" % [PoiInfo.RANKS[k], ranks[k]])
	md.append("- POI ranks (harder further out): %s." % ", ".join(rparts))
	md.append("")

	# --- Generation benchmark -------------------------------------------------------------
	var rng := RandomNumberGenerator.new()
	rng.seed = 4242
	md.append("## Generation benchmark (this machine, one thread)")
	md.append("")
	md.append("| Work | Time | Data size |")
	md.append("|---|---:|---:|")
	var lod_ms := []
	for lod in 3:
		var reps := 60
		var bytes := 0
		var tt := Time.get_ticks_usec()
		for i in reps:
			var d := gen.generate_chunk(Vector2i(rng.randi_range(-700, 700), rng.randi_range(-700, 700)), lod)
			bytes += d.estimate_bytes()
		var ms := (Time.get_ticks_usec() - tt) / 1000.0 / reps
		lod_ms.append(ms)
		md.append("| Chunk LOD%d (worker) | %.2f ms | %.0f KB |" % [lod, ms, bytes / 1024.0 / reps])
	var ft := FarTerrain.new()
	ft.setup(gen)
	var tt2 := Time.get_ticks_usec()
	for i in 30:
		ft.build_tile(Vector2i(rng.randi_range(-200, 200), rng.randi_range(-200, 200)), Vector2i(99999, 0), 8)
	md.append("| Far tile 64 x 64 m (worker) | %.2f ms | - |" % ((Time.get_ticks_usec() - tt2) / 1000.0 / 30))
	ft.free()
	var chunk := Chunk.new()
	chunk.library = PropLibrary.new()
	add_child(chunk)
	for lod in 3:
		var d := gen.generate_chunk(Vector2i(3, 4), lod)
		var tb := Time.get_ticks_usec()
		for i in 10:
			chunk.build(d)
		md.append("| Chunk LOD%d build (main thread) | %.2f ms | - |" % [lod, (Time.get_ticks_usec() - tb) / 10000.0])
	chunk.queue_free()
	var view := 0
	for dz in range(-9, 10):
		for dx in range(-9, 10):
			if Vector2(dx, dz).length() <= 9.5:
				view += 1
	var cores := OS.get_processor_count()
	md.append("")
	md.append("- A full view (%d chunks: LOD0 r3, LOD1 r6, LOD2 r9) costs about %.0f ms of worker time." % [view,
		37 * lod_ms[0] + 100 * lod_ms[1] + (view - 137) * lod_ms[2]])
	var full_h := TerrainGenerator.WORLD_CHUNK_COUNT * float(lod_ms[0]) / 1000.0 / 3600.0
	md.append("- Generating every chunk of the world at LOD0 would take %.1f CPU-hours (%.1f h on %d cores) - which is why" % [full_h, full_h / maxi(1, cores - 1), cores])
	md.append("  the world is never pre-generated: chunks are generated on demand and only changes are saved.")
	md.append("- Saved data grows only with what the player changes: one region file (32 x 32 chunks) holding a")
	md.append("  few dozen felled trees is a few hundred bytes (ZSTD).")
	md.append("")
	var f := FileAccess.open(_out, FileAccess.WRITE)
	if f:
		f.store_string("\n".join(md) + "\n")
		f.close()
		print("world survey written to ", ProjectSettings.globalize_path(_out))
	else:
		push_error("cannot write " + _out)
	print("\n".join(md))
	get_tree().quit()


static func _thousands(v: int) -> String:
	var s := str(absi(v))
	var out := ""
	while s.length() > 3:
		out = "," + s.substr(s.length() - 3) + out
		s = s.substr(0, s.length() - 3)
	return ("-" if v < 0 else "") + s + out
