class_name Achievements
## Achievement and stat definitions (Milestone 13). The ids double as the
## Steamworks API names (see platform/steam/achievements.csv, generated by
## tools/export_steam_config.gd).

## id, name, description, stat (progress counter or ""), goal, hidden
const LIST := [
	[&"first_craft", "Handy", "Craft your first item.", &"items_crafted", 1, false],
	[&"master_crafter", "Master Crafter", "Craft 500 items.", &"items_crafted", 500, false],
	[&"lumberjack", "Lumberjack", "Fell 100 trees.", &"trees_felled", 100, false],
	[&"homestead", "Homestead", "Have 25 building pieces standing.", &"", 25, false],
	[&"first_blood", "First Blood", "Defeat a monster.", &"monsters_killed", 1, false],
	[&"slayer", "Slayer", "Defeat 500 monsters.", &"monsters_killed", 500, false],
	[&"boss_slayer", "Giant Killer", "Defeat a boss.", &"bosses_killed", 1, false],
	[&"dungeon_delver", "Dungeon Delver", "Clear a dungeon.", &"dungeons_cleared", 1, false],
	[&"s_rank", "Into the Abyss", "Clear an S-rank dungeon.", &"", 1, false],
	[&"level_10", "Seasoned", "Reach level 10.", &"", 10, false],
	[&"level_50", "Veteran", "Reach level 50.", &"", 50, false],
	[&"level_100", "Legend of the Shardlands", "Reach level 100.", &"", 100, false],
	[&"explorer", "Wanderer", "Discover 8 different biomes.", &"biomes_discovered", 8, false],
	[&"cartographer", "Cartographer", "Discover 25 points of interest.", &"pois_discovered", 25, false],
	[&"merchant", "Merchant Prince", "Trade goods worth 5,000 copper.", &"copper_traded", 5000, false],
	[&"defender", "Defender", "Repel a raid.", &"raids_repelled", 1, false],
	[&"spellbinder", "Spellbinder", "Learn 4 spells.", &"", 4, false],
	[&"legendary", "Forged in Starlight", "Craft a legendary item.", &"", 1, true],
	[&"crafting_100", "Artisan", "Reach 100 Crafting skill.", &"", 100, false],
	[&"together", "Better Together", "Play a co-op session with a friend.", &"", 1, false],
]

const STATS := [&"items_crafted", &"trees_felled", &"monsters_killed", &"bosses_killed", &"dungeons_cleared",
	&"biomes_discovered", &"pois_discovered", &"copper_traded", &"raids_repelled", &"deaths", &"distance_km"]


static func get_def(id: StringName) -> Array:
	for a in LIST:
		if a[0] == id:
			return a
	return []


static func display_name(id: StringName) -> String:
	var d := get_def(id)
	return d[1] if not d.is_empty() else String(id)
